# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UKMac Blog
subtitle: A Jekyll blog about Apple, Microsoft and other stuff.
email: scott@ukmac.net
description: >- # this means to ignore newlines until "baseurl:"
  UKMac.net is Scott Paterson's Blog about Apple, Microsoft, Enterprise IT amongst other things.
baseurl: /
url: https://ukmac.net
twitter_username: ukmac
github_username: ukmac
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Scott Paterson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Welcome to my Blog"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ukmac.net"
    - label: "Telford, UK"
      icon: "fa fa-map-marker"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ukmac"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ukmac"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ukmac"
    - label: "Strava"
      icon: "fab fa-fw fa-strava"
      url: "https://www.strava.com/athletes/2570377"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ukmac"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ukmac"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ukmac"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "disqus"
  disqus:
    shortname: "ukmac"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
prose:
  rooturl: ''
  siteurl: 'https://ukmac.net'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
