name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 0 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: 'https://ukmac.net/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
